version: '3'
services:
  db:
    container_name: psql
    restart: always
    image: psql
    build:
      context: ./db
    volumes:
      - ./db/data/:/var/lib/postgresql/data
      - ./db/config.conf:/etc/postgresql.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bVawU6etXvWwQgsR
      POSTGRES_DATABASE: special
    expose:
      - 5432

  graphql:
    container_name: graphql
    restart: always
    image: graphile/postgraphile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:bVawU6etXvWwQgsR@db:5432/special # To be moved to environment file
    ports:
      - 5000:5000
    command: ["postgraphile", "--connection", "postgres://postgres:bVawU6etXvWwQgsR@db:5432/special", "--host", "0.0.0.0", "--port", "5000", "--schema", "special"]
    links:
      - db

  redis:
    container_name: redis
    restart: always
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./db/redis/data/:/data
    entrypoint: redis-server --appendonly yes

  queue:
    container_name: queue
    restart: always
    image: queue
    build:
      context: ./middleware/queue
    depends_on:
      - graphql
    environment:
      DEV: auth:*
      GRAPHQL_SERVER: graphql
    expose:
      - 3000
    ports:
      - 4000:3000
    links:
      - graphql

  moss:
    container_name: moss
    restart: always
    image: moss
    build:
      context: ./middleware/moss
    depends_on:
      - graphql
      - redis
    environment:
      DEV: auth:*
      GRAPHQL_SERVER: graphql
      REDIS_SERVER: redis
    expose:
      - 3050
    ports:
      - 4050:3050
    links:
      - graphql
      - redis

  allocate:
    container_name: allocate
    restart: always
    image: allocate
    build:
      context: ./middleware/allocate
    depends_on:
      - graphql
      - redis
    environment:
      DEV: auth:*
      GRAPHQL_SERVER: graphql
      REDIS_SERVER: redis
    expose:
      - 3051
    ports:
      - 4051:3051
    links:
      - graphql
      - redis

  dashboard:
    container_name: dashboard
    restart: always
    image: server
    build:
      context: ./frontend
    depends_on:
      - queue
      - moss
      - allocate
    environment:
      VUE_APP_QUEUE_PORT: 4000
      VUE_APP_MOSS_PORT: 4050
      VUE_APP_ALLOC_PORT: 4051
    ports:
      - 5678:8080
    links:
      - queue
      - moss
      - allocate
